### ISSUE TITLE
Clarify comments on `gen-ca` example fields, rename some

### ISSUE THREAD

**Issue by ZackButcher** [tetratelabs/istio-distro.io#136]
It's not clear to me what `secretFilePath` does from our docs:

https://github.com/tetratelabs/getistio.io/blob/13e2c677270f812edb6ebaf8620dcdb3f1052974/content/en/istio-ca-certs-integrations/gcp-cas-integration/_index.md#L38-L39

It _looks_ like that's the file path for the certs on disk? If so, we should spell it out, and say that if it's omitted it defaults (to `~/.getistio/secret/`). IMO I'd probably even just remove from the examples.

----

Related, I think the `force` field is a bit tough to understand ATM as well; I'd call it `overrideExistingCACertsSecret` or similar.

https://github.com/tetratelabs/getistio.io/blob/13e2c677270f812edb6ebaf8620dcdb3f1052974/content/en/istio-ca-certs-integrations/gcp-cas-integration/_index.md#L40-L42

**Comment by ZackButcher** [comment]
(The rename needs to be done in https://github.com/tetratelabs/getistio of course; I'll go file an issue over there)

**Comment by peterj** [comment]
I'll remove the `secretFilePath` from the current examples for now. We should have the docs for all possible fields somewhere.
