### ISSUE TITLE
netlify tests fail due Ubuntu version

### ISSUE THREAD

**Issue by PetrMc** [tetratelabs/istio-distro.io#269]
while doing PR for documentation update [PR](https://github.com/tetratelabs/istio-distro.io/pull/268) it was discovered that all tests for Netlify can't be run (and turn to fail state due outdated Ubuntu version).

```
10:12:45 AM: ---------------------------------------------------------------------
  UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

  To enable builds for this site, select a later build image at the following link:
  https://app.netlify.com/sites/getistio-demo/settings/deploys#build-image-selection

  For more details, visit the build migration guide:
  https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
  ---------------------------------------------------------------------
```

@deva26 / @pmerrison / @MB-Designs / @peterj / @Marc-Morata-Fite / @psbrar99 - I wouldn't mind looking into it but don't have access to Netfly - can one of you help me with getting access? 

Thank you!

**Comment by dio** [comment]
This is fixed. Should we rebuild?

**Comment by PetrMc** [comment]
all fixed - thank you!
