### ISSUE TITLE
Links, Metadata Display

### ISSUE THREAD

**Issue by theseanodell** [tetratelabs/istio-distro.io#61]
Can we fix the link/metadata to display in the following fashion?

[TechCrunch Example](https://techcrunch.com/2021/02/01/databricks-raises-1b-at-28b-valuation-as-it-reaches-425m-arr/)
Example - <img width="737" alt="Screen Shot 2021-02-03 at 10 30 49" src="https://user-images.githubusercontent.com/9096060/106777837-f7ead300-660a-11eb-8ab9-3af2528ac9b8.png">

[GetIstio Site](https://getistio-demo.netlify.app/blog/demo-2/)

Currently link/metadata is showing as follows: <img width="621" alt="Screen Shot 2021-02-03 at 10 32 26" src="https://user-images.githubusercontent.com/9096060/106778018-249eea80-660b-11eb-82c8-3ee9f3724459.png">

The current view shows no image, text that is no where to be found in the article.

**Comment by lunchboxav** [comment]
Thanks for submitting this issue Sean, I'll see what I can do.

**Comment by peterj** [comment]
I think this should be fixed once we add the meta tags for SEO (i.e. adding the twitter:card and image - I am not sure though if Hugo supports per-page Twitter cards).

**Comment by peterj** [comment]
Also, we should add more stuff to the meta tags, because it looks very empty.

![Screen Shot 2021-02-08 at 5 32 05 PM](https://user-images.githubusercontent.com/11080940/107303297-a8097300-6a33-11eb-9a66-0a0306388d61.png)

**Comment by lunchboxav** [comment]
Yes, @peterj it's next on my list. Btw, how do you test that @peterj ?

**Comment by peterj** [comment]
Perfect! I use the https://cards-dev.twitter.com/validator to see how the link would show up on Twitter.

**Comment by lunchboxav** [comment]
Thanks for that Peter, will give it a go
